server:
  port: 9097
spring:
  application:
    name: guanxiu_App
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://***.168.0.117:23306/potato_engineoil?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: *****
    password: ****
  redis:
    host: 192.168.0.***
    port: ***
    password: ***
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


sendMsg:
  templateCode: ****
  accessKeyId: 加密
  secret: 自己的密码，不要暴露
